services:
  portal-hub:
    build:
      context: ..
      dockerfile: web-apps/portal-hub/Dockerfile
    container_name: ${PORTAL_HUB_CONTAINER_NAME:-telemetry-portal-hub}
    ports:
      - "${PORTAL_HUB_HOST_PORT:-9500}:80"
    restart: on-failure
    networks:
      - default
      - shared

networks:
  shared:
    external: true
    name: ${SHARED_NETWORK_NAME:-ds-shared}
