spring.application.name=telemetry-storage-consumer
server.port=9504
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55432/telemetry}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:telematics}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:telematics}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
